### PR TITLE
feat: Avoid vertex and edge sequences in attributes

### PR DESCRIPTION
**Pull request by krlmlr**
For #807.

### CODE REVIEW

**Comment by krlmlr** [comment]
This is branched off of v1.4.2, running revdepchecks now.

**Comment by krlmlr** [comment]
No problems at all!

https://github.com/igraph/rigraph/pull/808/files#diff-bbdda7f28391ee0ec001638e5603609582124345e0d65ebd4747cc592f9bd56dR1

I suggest we include this into the upcoming 1.4.3 release, to avoid problems like #807.

**Review by ntamas — APPROVED** [review]

**Comment by szhorvat** [comment]
> I suggest we include this into the upcoming 1.4.3 release, to avoid problems like #807.

Since 1.4.3 is published, how about a 1.4.4? If you do go ahead with a 1.4.4, can you please update the C core to the latest commit on this branch, to include an additional fix? The commit message explains the fix. https://github.com/igraph/igraph/tree/release/0.9

**Comment by szhorvat** [comment]
Ah, I see these commits _were_ already included. I was confused by looking at the LTO checks on CRAN, but those are outdated, still showing information not even for 14.2, but for 1.4.1?  Why would that be so?

https://www.stats.ox.ac.uk/pub/bdr/LTO/igraph.out

Notice this warning:

```
core/community/leading_eigenvector.c:156:12: warning: ‘igraph_i_community_leading_eigenvector2’ defined but not used [-Wunused-function]
```

This is for the 1.4.1 sources, as this warning was already eliminated for 1.4.2.

**Comment by krlmlr** [comment]
CRAN keeps asking if LTO issues have been fixed, I keep telling them that we fix in igraph > 1.4.99 because of the C library update. Nothing to worry about for now.

**Comment by szhorvat** [comment]
These are not real issues. They are invalid warnings from GCC. As far as I'm concerned, this is a GCC bug.

**Comment by krlmlr** [comment]
I've seen CRAN in one instance accept LTO warnings as GCC bugs, we'll see.

**Comment by krlmlr** [comment]
Need to double-check if this is really needed or if perhaps there might be other ways to resolve this.

**Comment by szhorvat** [comment]
With igraph 0.10, which has been significantly cleaned up, it will be much easier to show that these are likely GCC problem.

**Comment by krlmlr** [comment]
After reviewing `` `[.igraph.vs`() ``, I am now confident that this is a good solution.

@mbojan: We do support arbitrary vectors, but vertex and edge sets create an unhealthy back reference that our code isn't prepared to deal with.

**Comment by mbojan** [comment]
Thanks @krlmlr , that definitely makes sense to me. I already tried the version from the PR 👍

**Pull request merged**
