### PR TITLE
docs: New `vignette("deprecated-dot-case")` that lists deprecated functions and their alternatives

### PR DESCRIPTION
**Pull request by maelle**
Draft as long as the main build isn't fixed. Locally it's knit without any issue :innocent: 

@krlmlr this is the article we had discussed.

### CODE REVIEW

**Comment by krlmlr** [comment]
dplyr needed too: https://github.com/igraph/rigraph/actions/runs/7248241585/job/19743772732?pr=1013#step:6:806

**Review by krlmlr — COMMENTED** [review]
Thanks. I'd prefer if the harvesting step would be carried out only once, storing a plain text file (CSV/JSON) in this repo.

**Comment by maelle** [comment]
That's indeed a much better idea :sweat_smile:

**Comment by krlmlr** [comment]
Is this ready to go?

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
