### PR TITLE
fix: Restore `hrg_tree()` semantics

### LINKED ISSUE #1047: Investigate behavior change in `hrg_tree()`
Old attributes?

https://github.com/igraph/rigraph/pull/1038#issuecomment-1872490707

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #1047.

### CODE REVIEW

**Comment by szhorvat** [comment]
I have not tested but it looks good!

**Comment by szhorvat** [comment]
You might want to add a quick test to verify that nothing changed since 1.6.0.

**Comment by krlmlr** [comment]
I'm merging this, given that we don't have examples or tests, and no CRAN packages uses `hrg_tree()` .

**Comment by szhorvat** [comment]
It's totally up to you how many tests you add. This is a very straightforward fix, I don't think a test is critical.

**Pull request merged**
