### PR TITLE
chore: Reduce warnings from `R CMD check`

### PR DESCRIPTION
**Pull request by krlmlr**
For #1006.

### CODE REVIEW

**Comment by szhorvat** [comment]
It seems that it's including `src/vendor/igraph_export.h`. That's the file you need to modify.

I'm not sure why `igraph_export.h` is in `tools/stimulus`, but it doesn't seem to be used anymore. @Antonov548, do you know why that file is there?

**Comment by Antonov548** [comment]
> It seems that it's including `src/vendor/igraph_export.h`. That's the file you need to modify.
> 
> I'm not sure why `igraph_export.h` is in `tools/stimulus`, but it doesn't seem to be used anymore. @Antonov548, do you know why that file is there?

I think it's there because file from `tools/stimulus` is replacing the file in `src/vendor` after call `Makefile-cigraph` which basically makefile for vendoring igraph

**Comment by szhorvat** [comment]
> file from `tools/stimulus` is replacing the file in `src/vendor` after call `Makefile-cigraph`

That's not actually happening. After running `make -f Makefile-cigraph` I still see `#define IGRAPH_DEPRECATED __attribute__ ((__deprecated__))` in `src/vendor/igraph_export.h`.

**Comment by Antonov548** [comment]
> > file from `tools/stimulus` is replacing the file in `src/vendor` after call `Makefile-cigraph`
> 
> That's not actually happening. After running `make -f Makefile-cigraph` I still see `#define IGRAPH_DEPRECATED __attribute__ ((__deprecated__))` in `src/vendor/igraph_export.h`.

Yes, you are right. I have created pull reuqest: https://github.com/igraph/rigraph/pull/1089

**Comment by krlmlr** [comment]
Thanks, good catch!

**Pull request merged**
