### PR TITLE
chore: `R_SEXP_to_igraph()` and `R_SEXP_to_igraph_copy()` get `igraph_t` object from external pointer

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Comment by Antonov548** [comment]
refactoring for 0.10 to handle `cache` in `igraph_t`

**Review by krlmlr — COMMENTED** [review]
Brilliant, thanks! I could release this and more refactorings (if needed) as 1.5.1.

Can you please merge this into #840 first?

**Comment by Antonov548** [comment]
> oldrel-1

Yes, I will merge it. oldrel-1 failed for some reason which is not related to changes I think.

**Comment by krlmlr** [comment]
This does look like a protection error, but it's unclear where that came from.

Checking on top of v1.5.0: https://github.com/igraph/rigraph/actions/runs/5437288024

**Comment by krlmlr** [comment]
Also on the new r-1.5 branch, with R 4.2 on my system:

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

g <- make_ring(3)

gctorture(10001)
for (i in 1:3) {
  print(i)
  g <- add_vertices(g, 3)
}
#> [1] 1
#> Error in add_vertices(g, 3): VECTOR_ELT() can only be applied to a 'list', not a 'integer'
```

<sup>Created on 2023-07-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Can you replicate?

**Comment by krlmlr** [comment]
Something's not quite right in the realm of attribute handling. I added a commit that fixes the problem, but I don't think this should be even necessary. That commit might introduce a memory leak: R objects that are never freed.

I don't understand the global (!!!) `R_igraph_attribute_protected` and `R_igraph_attribute_protected_size` variables. I do think we need to step back and, once more, clean this up before proceeding with 0.10.

**Comment by krlmlr** [comment]
This is now mergeable, but we should definitely understand what's going on here.

**Comment by krlmlr** [comment]
I started revdepchecks on the current main branch. If they pass, we can continue working on the main branch, and switch to "baby step" mode again.

**Comment by krlmlr** [comment]
@Antonov548: I'm pretty sure that my last commit is bad, but I can't quite understand how to fix correctly.

**Comment by Antonov548** [comment]
> I'm pretty sure that my last commit is bad, but I can't quite understand how to fix correctly.

I also not sure about this changes. I tried play around with attributes - this changes works but still don't understand in details how they works. I think if this `preserve` also should be in the copy graph function.

**Comment by szhorvat** [comment]
I am not familiar with R's C API, I just wanted to point out that `igraph_copy()` will invoke `R_igraph_attribute_copy()`. If that function does the attribute copying properly, then `R_SEXP_to_igraph_copy()` should not change attributes explicitly.

**Comment by krlmlr** [comment]
This runs correctly on top of #870.

**Comment by krlmlr** [comment]
It's weird that I can't seem to add a test in the spirit of https://github.com/igraph/rigraph/pull/870/files#diff-2f53a23080d87ca119f5c65194b7cf9df808dd6e77ac201309b45f4dd7231830R39-R47 . But we can still check manually before merging.

Let's merge the other PRs and further simplify this PR afterward.

**Comment by krlmlr** [comment]
I updated with rebase, this amounts to a force-push.

Can you please further simplify? I think both routines shouldn't need to touch the `->attr` component anymore.

**Comment by Antonov548** [comment]
> Can you please further simplify? I think both routines shouldn't need to touch the `->attr` component anymore.

84 tests are failed if `->attr` is not assigned.

**Comment by Antonov548** [comment]
> Can you please further simplify? I think both routines shouldn't need to touch the `->attr` component anymore.

I can't get why it's not needed anymore. Since attributes is still part of list structure with `igraph_t_idx_attr` index.

**Comment by krlmlr** [comment]
I think I understand why we need the attribute copy in `R_SEXP_to_igraph()` : The attributes may have changed from the R side without updating the C structure, this takes care of it.

I don't understand why we need it in `R_SEXP_to_igraph_copy()`, I added a FIXME so that we can review later.

**Comment by Antonov548** [comment]
@krlmlr are we okay to merge this?

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
