### PR TITLE
Update build-requirements.txt

### PR DESCRIPTION
**Pull request by maelle**
@Antonov548 does a tag need to be created or would this work?

Context https://github.com/igraph/rigraph/pull/1229#discussion_r1484238950

### CODE REVIEW

**Comment by Antonov548** [comment]
I think it might work. 
Previously we were try to keep some version of stimulus. Maybe we can ask @ntamas to create new release. I just don't have permissions in stimulus repository.

**Comment by maelle** [comment]
@ntamas if you have time to create a new tag in the Stimulus repo, that'd be great :pray:

**Comment by szhorvat** [comment]
This works. Let's use this for the moment in the interest of getting the bugfix release out ASAP, as Tamás is travelling at the moment.

**Comment by maelle** [comment]
@szhorvat ok! What will this update exactly? In particular will this update the Docker stuff used in https://github.com/igraph/rigraph/blob/0dabc9ee8d77bb169288a7944f6079e6628d7147/src/README.md?plain=1#L23

**Comment by szhorvat** [comment]
This will use the new version of stimulus when you re-generate interfaces using

```
make -f Makefile-cigraph src/rinterface.c R/aaa-auto.R
```

**Comment by maelle** [comment]
Thanks! I wonder about the Docker stuff but I'll need to explore a bit more (I use Docker rather than make directly because it has worked better for me)

**Comment by ntamas** [comment]
Stimulus 0.21.5 is now tagged so you can use that. Note that you don't need a tag for quick fixes like this as you can point `build-requirements.txt` to a [specific Git commit hash](https://stackoverflow.com/a/35998253/156771) instead.

**Comment by maelle** [comment]
thank you!!

**Pull request merged**
