### PR TITLE
Speed up `as_adj_list` if igraph_opt("return.vs.es") is false

### PR DESCRIPTION
**Pull request by cfhammill**
Also updates the docs to point out that this option exists. Not a fully satisfying solution to #194, but provides a simple work around.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! I assume that you checked that after addind `create_vs`, it is still fast. :)

**Comment by cfhammill** [comment]
It is fast if you set igraph_options(return.vs.es = FALSE)  yes it is still fast. I don't know if `create_vs` could be sped up.

**Comment by vtraag** [comment]
@cfhammill , I guess that PR #197 renders this PR obsolete and should be preferred over this one?

**Comment by ntamas** [comment]
This PR seems to be superseded by #197 so I'm closing this.

**Pull request closed without merging**
