### PR TITLE
refactor: simplify code

### PR DESCRIPTION
**Pull request by maelle**
Now, maybe in `R_igraph_mybracket2_names` itself there could be a way to have the correct output directly?

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]
Thanks!

**Comment by krlmlr** [comment]
@Antonov548: Should this perhaps be moved to the C code?

**Comment by Antonov548** [comment]
> @Antonov548: Should this perhaps be moved to the C code?

Yes, maybe it's better to keep such things on C side.

**Comment by maelle** [comment]
@Antonov548 could you please  make a PR, or edit this branch, to put that change to the C code? Thank you!

**Comment by krlmlr** [comment]
Closing in favor of #1342.

**Pull request closed without merging**
