### PR TITLE
ci: run examples with sanitizer

### PR DESCRIPTION
**Pull request by Antonov548**
Closes: https://github.com/igraph/rigraph/issues/1195

Proof that it detects memory leaks in examples: https://github.com/igraph/rigraph/pull/1286

### CODE REVIEW

**Comment by szhorvat** [comment]
So does this mean that we're good, no crashes or leaks triggered by examples?

**Comment by Antonov548** [comment]
> So does this mean that we're good, no crashes or leaks triggered by examples?

Sanitizer showed some warnings about undefined behavior (or similar), but it doesn't cause the crash.

Yes, examples good.

**Comment by szhorvat** [comment]
> Sanitizer showed some warnings about undefined behavior

That may still indicate a real issue, though not with certainty. Would you be able to extract the full message? I can only see a partial thing here:

https://github.com/igraph/rigraph/actions/runs/8221181042/job/22481341484#step:5:6601

We can then fine-tune the specific checks UBSan does so that it only warns about real issues.

**Comment by szhorvat** [comment]
Never mind, I looked at line 80. We cast a real to integer and back to see if the real is representable as an integer. We do this on purpose, not an issue.

**Review by krlmlr — APPROVED** [review]
Nice, thanks!

**Comment by maelle** [comment]
@Antonov548 a limitation to `R2dex()` that I just realized is that it does not run the examples that are wrapped in `\dontrun{}`. I'll make a PR.

**Pull request merged**
