### PR TITLE
fix: comment failing ci

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Comment by Antonov548** [comment]
@krlmlr I didn't understand comment about `s/AppVeyor/Aviator/`. Is it what you suggest?

**Comment by krlmlr** [comment]
Yes, except we now have more failures 😱 

s/// is the vi command for search+replace. I made a typo in an earlier comment.

**Comment by Antonov548** [comment]
merged https://github.com/igraph/rigraph/pull/1356 to have happy CI.

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
