### PR TITLE
Extract version in `igraph_version.h` during vendoring

### PR DESCRIPTION
**Pull request by Antonov548**
Closes https://github.com/igraph/rigraph/issues/1259

A bit more compicated process of vendoring cigraph. But it extracts exact version from cigraph using cmake.
Since this only for dev team I think it should be fine.

### CODE REVIEW

**Comment by szhorvat** [comment]
I'm really not the right person to review this. Perhaps Tamás or Kirill should take a look instead.

A small request from me if possible: Let's keep the `--depth` large enough but still finite so that the amount downloaded is kept in check. This is useful when working with bad connections (on a train, in China, etc.)

**Comment by Antonov548** [comment]
> I'm really not the right person to review this. Perhaps Tamás or Kirill should take a look instead.
> 
> A small request from me if possible: Let's keep the `--depth` large enough but still finite so that the amount downloaded is kept in check. This is useful when working with bad connections (on a train, in China, etc.)

Good suggestion. I just not sure what will be enough to extract version information?

**Review by szhorvat — APPROVED** [review]
No objection from me, but again, I'm not the best person to review this.

Please don't let my `--depth` request become a blocker for merging this.

**Comment by szhorvat** [comment]
Would it be possible to break this up into several stages: first update the files, then commit. There would be multiple make targets, with the option to pull a certain branch of the C core and NOT commit the changes.

This would make it easier to test changes to the C core before merging them. I did this yesterday, but I did it manually: I edited the script to pull a certain branch, I let it commit the changes, and finally I undid the last commit.

All of this would be the topic of a future PR, of course.

**Comment by Antonov548** [comment]
> Would it be possible to break this up into several stages: first update the files, then commit. There would be multiple make targets, with the option to pull a certain branch of the C core and NOT commit the changes.
> 
> This would make it easier to test changes to the C core before merging them. I did this yesterday, but I did it manually: I edited the script to pull a certain branch, I let it commit the changes, and finally I undid the last commit.
> 
> All of this would be the topic of a future PR, of course.

I think it could be part of https://github.com/igraph/rigraph/issues/1261

**Comment by krlmlr** [comment]
The vendoring code for some reason kills the `.mk` files.

I'll install a GitHub Action that periodically updates the vendored C core, similarly to the duckdb R package.

**Comment by krlmlr** [comment]
Moved the important bits into the other PR.

I wonder if we also should run `cmake` in our `./configure` to generate the relevant headers, without using the full-fledged build environment generated by `cmake` . That would be very nice and indeed simplify our logic in `./configure` .

**Pull request closed without merging**
