### PR TITLE
comply with the compactness requirement of str

### PR DESCRIPTION
**Pull request by sam-s**
https://github.com/igraph/rigraph/issues/73
full=TRUE only if max.level is not supplied or bigger than 1

### CODE REVIEW

**Comment by gaborcsardi** [comment]
What's the `rev.igraph`?

**Comment by gaborcsardi** [comment]
Also, this is kind of an abuse of `max.level`, so I'll rather close this. Something that makes proper use of `max.level` would be fine, though. E.g. 
- `1`: only summary
- `2`: summary + edges
- `3`: sumamry + edges + all attributes
Maybe.

**Comment by sam-s** [comment]
@gaborcsardi: rev.graph: Reverse the direction of all edges.

**Comment by gaborcsardi** [comment]
Yes, I get that, but what does it have to do with this pull request?

**Comment by sam-s** [comment]
`str` is _required_ to always produce compact output.
it can _never_ print edges

**Comment by sam-s** [comment]
this was supposed to be a separate pull request.
I am not very good with these github tricks.
sorry.

**Pull request closed without merging**
