### PR TITLE
refactor: create helper function for code regeneration

### PR DESCRIPTION
**Pull request by maelle**
Related to #742

Questions

- what other files can be regenerated
- should there be a special value of file for regeneration all of them (NULL)

### CODE REVIEW

**Comment by krlmlr** [comment]
This is showing weird

```
fatal: detected dubious ownership in repository at '/root/workspace'
```

errors when run.

Why do we need an R wrapper for a shell call?

We can work together on cleaning up the process and the documentation.

**Comment by maelle** [comment]
> Why do we need an R wrapper for a shell call?

I thought it'd be smoother (since I am mostly working in the R console) but if it's not possible, I'll keep using the shell call.

**Comment by krlmlr** [comment]
Need to look at the error messages together.

**Comment by krlmlr** [comment]
We no longer run `make` in Docker, instead the `Makefile` contains `docker run` instructions.

**Pull request closed without merging**
