### PR TITLE
feat: `all_shortest_paths()` returns the vertex list in both `res` and `vpaths` components

### PR DESCRIPTION
**Pull request by krlmlr**
Are we doing this only because in 0.10 there will be an `edges` component?

### CODE REVIEW

**Comment by szhorvat** [comment]
Yes.

But I am not sure that `vertices` ans `edges` are the best names. We want consistency between all shortest path functions. Others have `vpath` and `epath` instead. `functions.yaml` contains `vertices` and `edges`. Whatever choice is made, it should be consistent between the different path functions.

**Comment by krlmlr** [comment]
Do we aim for consistency across all target languages?

**Comment by szhorvat** [comment]
> Do we aim for consistency across all target languages?

No, personally I am against that.

I was referring to consistency between different functions in R.

**Comment by krlmlr** [comment]
So, the plan would be to change all instances of `$vertices` to `$vpath`, and `$edges` to `$epath`, where appropriate?

**Comment by krlmlr** [comment]
`all_shortest_paths()` is the only relevant instance. Changed to `$vpaths` because it's a list of vpath-s.

**Comment by szhorvat** [comment]
> Conversely, we want an epaths component too.

This we cannot have in 1.6.0, as 0.9 does not provide the edge path, and the edge path cannot be reconstructed from the vertex path in case of multigraphs. It seems to me that we cannot do more in this PR.

**Comment by krlmlr** [comment]
Yeah, let's do `$epaths` for 0.10.

**Pull request merged**
