### PR TITLE
docs: improve "family" titles

### PR DESCRIPTION
**Pull request by maelle**
Extracted from #662

@krlmlr

### CODE REVIEW

**Comment by maelle** [comment]
@krlmlr I think that this can be merged.

**Comment by ntamas** [comment]
I'll merge this as I was looking at the docs today and got confused by some of the family titles. It would be nice to see an up-to-date list so I can know what needs to fixed still.

**Comment by maelle** [comment]
an up-to-date list of all existing families in the docs?

**Comment by ntamas** [comment]
I meant, an up-to-date everything as there were a few homepage-related PRs pending :)

**Comment by maelle** [comment]
what is expected of me reg that list?

**Comment by ntamas** [comment]
nothing, now that the homepage is updated with the PR I can see the current state of things just by going to https://igraph.github.io/rigraph

**Pull request merged**
