### PR TITLE
refactor: auto-generate `are_adjacent()`, avoid deprecated `igraph_are_connected()` C function

### LINKED ISSUE #1253: `igraph_are_adjacent()`
https://github.com/igraph/igraph/pull/2486

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes #1253

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. Seeing `-Waddress` warnings in https://github.com/igraph/rigraph/actions/runs/7944281043/job/21689682420?pr=1254#step:9:84:

```
  vendor/cigraph/src/community/leading_eigenvector.c:606:28: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
  vendor/cigraph/src/graph/visitors.c:261:21: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
  vendor/cigraph/src/graph/visitors.c:551:67: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
  vendor/cigraph/src/isomorphism/vf2.c:667:71: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
  vendor/cigraph/src/isomorphism/vf2.c:1504:71: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
  vendor/cigraph/src/misc/motifs.c:396:25: warning: the address of 'ret' will always evaluate as 'true' [-Waddress]
```

Could be a change in the build envionment, or related to this PR. New run: https://github.com/igraph/rigraph/actions/runs/7946903820

**Comment by szhorvat** [comment]
Forgot to re-add a manual patch after auto-generation.

**Comment by szhorvat** [comment]
Fixed.

**Comment by krlmlr** [comment]
Do we need two macros instead of one?

https://github.com/igraph/rigraph/compare/4b5fd0554f47303c08857734be444af498d1341c..2211c0f35c3642196c0e557892afc0d6e2f12e15

**Comment by szhorvat** [comment]
CC @ntamas since he added this macro originally.

I vote for changing the macro in the C core in the same way as above, as this warning has been a constant annoyance when testing with various compilers, and so far there has been no need for performing this NULL-check. But it should be decided by Tamás.

**Comment by krlmlr** [comment]
I suspect it could be replaced with a static assert?

**Comment by ntamas** [comment]
That macro was the usual defensive programming habit from my side. If we can replace the check with a static assert, that's great. If we can't, let's add a runtime assert instead if possible.

**Pull request merged**
