### PR TITLE
fix: `as.hclust(hrg.fit(g))` works again

### PR DESCRIPTION
**Pull request by krlmlr**
For #720.

### CODE REVIEW

**Comment by krlmlr** [comment]
@Antonov548: can you please propose a change that uses `.Call()` instead of `.C()` so that we can later integrate in #720?

**Comment by krlmlr** [comment]
This probably needs documentation and an example too, CC @maelle.

Nobody ever complained (on the issue tracker) that this doesn't work.

**Review by ntamas — APPROVED** [review]
Looks good to me. I leave the merging up to you.

**Comment by krlmlr** [comment]
@maelle: Can you please handle examples and documentation at some point?

**Pull request merged**
