### PR TITLE
chore: Prepare move to igraph 0.10

### PR DESCRIPTION
**Pull request by krlmlr**
Extracted from #840.

@Antonov548: I wonder if we can do "small bets" here again: refactor code before actually moving to igraph 0.10. Would that approach work in principle?

I tried adding more commits from that PR, but compilation a40lready broke.

### CODE REVIEW

**Comment by krlmlr** [comment]
Oh, the tests fail now. That's too bad.

**Comment by Antonov548** [comment]
> Oh, the tests fail now. That's too bad.

I can check why tests are failed in this case. But I think it could be because R functions didn't change accordingly.

I would love to move by small pull request. But sometimes it's hard to seperate such small parts from the big list of commpilation errors. And I think it can slow down the process a lot.

**Comment by Antonov548** [comment]
> Yes, I see this. Let's keep going with the big PR then.

Also I would like to run some static analyzer after fix coompilation errors to get rid of not used functions and declaration in `rinterface_extra.c`.

**Comment by szhorvat** [comment]
Once you set up CMake, static analysers will be much easier to use. For example, CMake can generate Xcode project files, and you can use Xcode's Project -> Analyze feature, which presents the results in a very easy to understand format.

For the C core, we are currently using https://scan.coverity.com/, which is also very good.

**Pull request closed without merging**
