### PR TITLE
docs: Improve `min_st_separators()` documentation

### PR DESCRIPTION
**Pull request by szhorvat**
@maelle Is this the best way to comment on examples? Can we comment using normal text that includes math instead of writing code comments? If yes, can you push to this branch and demonstrate?

### CODE REVIEW

**Comment by maelle** [comment]
Good question!

We can't have maths in example but a workaround would be to create an arbitrary section using R Markdown support. The code in the code chunk is evaluated every time the `document()` function is run,
- which seems fine as far as time is concerned as this is fast code apparently;
- which made me add the same code as a test case.

https://roxygen2.r-lib.org/articles/rd-formatting.html#code-chunks

Note that the section name is currently really bad. :grin:

**Comment by szhorvat** [comment]
Thank you!

**Comment by szhorvat** [comment]
A problem is that every time we re-generate docs, something changes:

image

Should we do something about this?

Perhaps we should just go with the original code comment version? The math is actually not that important for this specific example.

**Comment by krlmlr** [comment]
In the tests, we have `local_igraph_options(print.id = FALSE)` to inhibit this, but I'm not sure what's the best way to use this with a roxygen2 example.

@maelle: Can you help please?

**Comment by maelle** [comment]
Probably not the best solution as this is an unexported function :zany_face: (so especially confusing for users) I need to make it work to put the call in a separate chunk (using the `.in` argument), will try again later this week.

**Comment by szhorvat** [comment]
Let's just add the comments as an actual code comment, problem solved. Agreed?

I would rather not add distracting code to an example which is making an important  point about how a function behaves.

**Comment by maelle** [comment]
I'll experiment with a knitr hook to modify the output without a comment. I fear the comment is distracting too.

**Pull request merged**
