### PR TITLE
docs: replace `graph()` with `make_graph()` in examples

### LINKED ISSUE #736: deprecation loop
- `graph()` is deprecated to `make_graph()`.
- `make_graph` calls `graph_from_literal()`.
- `graph_from_literal()` calls `graph_from_literal_i()` that calls `graph()`. :zany_face: 

That is a problem with the lifecycle changes in https://github.com/igraph/rigraph/pull/716

Is the best solution to remove all calls to `graph()` in the main branch, then I'll rebase my PR? 

ccc @krlmlr

### PR DESCRIPTION
**Pull request by maelle**
Fix  #736

### CODE REVIEW

**Comment by ntamas** [comment]
LGTM. :+1:

**Comment by krlmlr** [comment]
I'll take a closer look at my igraph inbox later today. 🌋

**Comment by ntamas** [comment]
No, it's just unclear whether I can pull the trigger on it or we are waiting for @krlmlr :)

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
