### PR TITLE
fix: update obsolescent character length declarations in ARPACK Fortr…

### LINKED ISSUE #1533: CRAN Fortran warning: Obsolescent feature: Old-style character length at (1)
Continuing from https://github.com/igraph/igraph/issues/551#issuecomment-2378114968

```
gfortran-14 -fvisibility=hidden -fpic  -g -O2 -mtune=native -Wall -pedantic  -c vendor/arpack/dmout.f -o vendor/arpack/dmout.o
vendor/arpack/dmout.f:34:19:

   34 |       CHARACTER*80       LINE
      |                   1
Warning: Obsolescent feature: Old-style character length at (1)
```

### PR DESCRIPTION
**Pull request by szhorvat**
…an code

fixes #1533

### CODE REVIEW

**Comment by szhorvat** [comment]
Can you please test this in the same manner as CRAN does, @krlmlr ?

**Comment by szhorvat** [comment]
I believe the CI failures are not related to the changes in this PR.

**Comment by krlmlr** [comment]
Thanks. I'll backport to 2.1.0 and resubmit.

**Review by krlmlr — APPROVED** [review]

**Comment by krlmlr** [comment]
Included in the main branch, release pushed. Thanks!

**Pull request closed without merging**
