### PR TITLE
WIP: Add coverage reporting

### PR DESCRIPTION
**Pull request by krlmlr**
With tweaks to CI/CD.

### CODE REVIEW

**Comment by szhorvat** [comment]
We use Codecov for the C library. https://app.codecov.io/gh/igraph/igraph

Is it possible / does it make sense to use it for R as well? It provides an excellent interface for exploring coverage information.

**Comment by krlmlr** [comment]
Yes, absolutely -- coverage reports will be uploaded to codecov. I'm adding relevant parts of your `codecov.yml` here.

**Comment by szhorvat** [comment]
An interesting future project would be to investigate how much of C/igraph is covered by the R/igraph test suite. This would include the C glue code between R and igraph, and would help prioritize the coverage work for C/igraph.

**Comment by krlmlr** [comment]
I'm currently filtering out the vendored and imported source, on purpose. It can be added easily later on, see `line_exclusions` .

**Comment by krlmlr** [comment]
@ntamas: I'm repeatedly seeing spurious test failures, e.g., https://github.com/igraph/rigraph/actions/runs/3689217836/jobs/6245005389. We should watch out for those.

**Comment by szhorvat** [comment]
@ntamas Do you understand why it's non-deterministic, though? Parallelization?

**Comment by ntamas** [comment]
I don't understand completely, but the failing test case relies on eigenvector calculations, which eventually use BLAS/LAPACK from R, and who knows which version/variant is included in R (and whether it's parallelized over multiple CPU cores).

**Comment by krlmlr** [comment]
I don't know a lot about Git submodules, but I'm seeing the following:

```
> g l .gitmodules
* commit d3f397208364acef755d610b8230d2e4eace76e0
| Author: Gábor Csárdi <csardi.gabor@gmail.com>
| Date:   Sun Jan 27 16:55:10 2019 +0000
|
|     Update  C igraph submodule
|
|     We are using a cran branch now.
|
| 1     1       .gitmodules
|
* commit e06cabd4d72db70924e592ad3738cbe0990d5a70
| Author: Gabor Csardi <csardi.gabor@gmail.com>
| Date:   Fri Jan 16 17:01:25 2015 -0500
|
|     cigraph module to latest C lib, master branch
|
| 1     1       .gitmodules
|
* commit ed261dfd3b075acdcd9cd6d4157468e401946173
  Author: Gabor Csardi <csardi.gabor@gmail.com>
  Date:   Tue Jan 6 11:49:18 2015 -0500

      Add C igraph as a submodule

  4     0       .gitmodules
```

Does this mean we're running on a 2019 version of the C library?

**Comment by krlmlr** [comment]
I'm now seeing that the submodule points to the `cran` branch, and that it contains igraph/igraph@a4c955d2b10f5470dd8b123f088ae09b919d2f17.

**Comment by ntamas** [comment]
No that's not where it points to at the moment. The contents of the `.gitmodules` file does not give you the full picture; the ground truth is in `.git/modules/cigraph/HEAD`.

Screenshot 2022-12-13 at 22 21 35

**Comment by ntamas** [comment]
It seems like you need to check the log of the folder itself; this is the raw content of the blob where we last updated the submodule:

Screenshot 2022-12-13 at 22 24 00

**Comment by krlmlr** [comment]
Thanks, got it.

The easiest way to "fix" the tests is to skip them on older R versions, I believe I only ever saw R 3.4 and R 3.5 failing.

**Review by ntamas — APPROVED** [review]
Thanks a lot!

**Pull request merged**
