### PR TITLE
docs: update allcontributors table

### LINKED ISSUE #1239: update allcontributors table in README
- how do we want to update this table regularly?
- my name is not igraph :joy_cat:

### PR DESCRIPTION
**Pull request by maelle**
Fix #1239

But I think not all contributors are detected.

### CODE REVIEW

**Comment by mpadge** [comment]
@maelle You were right. https://github.com/ropenscilabs/allcontributors/issues/42 has fixed the issue. thanks :+1:

**Comment by maelle** [comment]
@mpadge I'm confused
``` r
allcontributors::get_contributors("igraph", "rigraph")
#> ★  Extracting code contributors
#> ✔ Extracted code contributors
#> ★  Extracting github issue contributors
#> ✔ Extracted github issue contributors
#> ★  Checking GitHub URLs
#> ✔ Checked GitHub URLs
#>          logins contributions
#> 1   gaborcsardi          1504
#> 2        krlmlr          1012
#> 3        maelle           865
#> 4        ntamas           508
#> 5      szhorvat           281
#> 6    Antonov548           181
#> 7      adalisan            16
#> 8      dmurdoch             6
#> 9       olivroy             3
#> 10       hadley             2
#> 11     clpippel             2
#> 12   wael-sadek             2
#> 13      peranti             1
#> 14       raulzr             1
#> 15       zeehio             1
#> 16         smoe             1
#> 17        mirca             1
#> 18     a-lambda             1
#> 19     person-c             1
#> 20     etheleon             1
#> 21       stnava             1
#> 22     kasterma             1
#> 23     clhunsen             1
#> 24        qsz13             1
#> 25      QuLogic             1
#> 26 Hosseinazari             1
#> 27       jeroen             1
#> 28      reuning             1
#> 29   MajoroMask             1
#>                                                   avatar type
#> 1     https://avatars.githubusercontent.com/u/660288?v=4 code
#> 2    https://avatars.githubusercontent.com/u/1741643?v=4 code
#> 3    https://avatars.githubusercontent.com/u/8360597?v=4 code
#> 4     https://avatars.githubusercontent.com/u/195637?v=4 code
#> 5    https://avatars.githubusercontent.com/u/1212871?v=4 code
#> 6   https://avatars.githubusercontent.com/u/22891541?v=4 code
#> 7    https://avatars.githubusercontent.com/u/1790714?v=4 code
#> 8    https://avatars.githubusercontent.com/u/1935680?v=4 code
#> 9   https://avatars.githubusercontent.com/u/52606734?v=4 code
#> 10      https://avatars.githubusercontent.com/u/4196?v=4 code
#> 11   https://avatars.githubusercontent.com/u/9609214?v=4 code
#> 12  https://avatars.githubusercontent.com/u/42678896?v=4 code
#> 13   https://avatars.githubusercontent.com/u/9472741?v=4 code
#> 14  https://avatars.githubusercontent.com/u/13007941?v=4 code
#> 15     https://avatars.githubusercontent.com/u/75441?v=4 code
#> 16    https://avatars.githubusercontent.com/u/207407?v=4 code
#> 17  https://avatars.githubusercontent.com/u/13077051?v=4 code
#> 18 https://avatars.githubusercontent.com/u/155024809?v=4 code
#> 19  https://avatars.githubusercontent.com/u/93318795?v=4 code
#> 20   https://avatars.githubusercontent.com/u/2868858?v=4 code
#> 21    https://avatars.githubusercontent.com/u/324222?v=4 code
#> 22    https://avatars.githubusercontent.com/u/421437?v=4 code
#> 23   https://avatars.githubusercontent.com/u/2649820?v=4 code
#> 24   https://avatars.githubusercontent.com/u/4075761?v=4 code
#> 25    https://avatars.githubusercontent.com/u/302469?v=4 code
#> 26    https://avatars.githubusercontent.com/u/971459?v=4 code
#> 27    https://avatars.githubusercontent.com/u/216319?v=4 code
#> 28   https://avatars.githubusercontent.com/u/6343832?v=4 code
#> 29  https://avatars.githubusercontent.com/u/19700954?v=4 code
```

<sup>Created on 2024-10-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
So I get only code contributors and not even enough of them.

**Comment by maelle** [comment]
@mpadge the problem is with the URL checking, I'll turn it off for now.

**Pull request merged**
