### PR TITLE
feat!: advance lifecycle deprecation from soft to warn

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by krlmlr** [comment]
Happy to run revdepchecks once the build is green.

**Comment by maelle** [comment]
@krlmlr the build is green now :innocent: could you please run revdeps checks? :pray: thank you!

**Comment by krlmlr** [comment]
Nice! I'd like to tackle this after the 2.0.0 release. The goal of that release is to use the new C core.

**Comment by maelle** [comment]
What's the next version number? Could you please run revdeps checks for this branch?

**Comment by krlmlr** [comment]
For the change from soft to warn, do we really advance the version number?

I feel it's a little too early for that. Should we first move everything to {lifecycle} and give downstream some time to adapt? I suspect most users aren't even aware of the API change.

**Comment by maelle** [comment]
> For the change from soft to warn, do we really advance the version number?

Oh right, no.

> I feel it's a little too early for that. Should we first move everything to {lifecycle} and give downstream some time to adapt? I suspect most users aren't even aware of the API change.

Ok.

**Pull request closed without merging**
