### PR TITLE
feat: Rename arguments to `assortativity(values, values.in)` from `types1` and `types2`

### PR DESCRIPTION
**Pull request by krlmlr**

### CODE REVIEW

**Comment by krlmlr** [comment]
This is the last interface incompatibility introduced in the igraph-0.10 branch, as far as I can tell. Merging it here to decouple interface changes from library updates.

@szhorvat: Please confirm that this is intended.

**Comment by szhorvat** [comment]
Yes, intended.

**Review by szhorvat — APPROVED** [review]

**Comment by krlmlr** [comment]
`assortativity_nominal()` still has `types`, should we update that too?

**Comment by szhorvat** [comment]
> `assortativity_nominal()` still has `types`, should we update that too?

No, because those are actually types, i.e. it's a categorical variable.

**Pull request merged**
