### PR TITLE
coerse membership to a factor before as.numeric

### PR DESCRIPTION
**Pull request by aghaynes**
this should allow strings to be passed as membership, rather than just numerics.

### CODE REVIEW

**Comment by aghaynes** [comment]
my motivation for this is that RStudio/R completely crashed (without any error message) when I used a string rather than a numeric.

**Comment by vtraag** [comment]
Thanks for contributin this @aghaynes! It would indeed be nice to have "named" communities, so that arbitrary vectors would also be suitable as membership, and that these names would also be consistently used throughout the code base. However, this is a much more extensive change. By allowing this in only a single function (`modularity`), but not elsewhere, this will presumably raise questions.

Instead of allowing arbitrary vectors to be used as an input for `modularity`, I think it would be better to simply raise an error and stop if the membership is not numerical. This should also prevent R from crashing, I would think. If have opened PR #455 to address this. Could you take a look to try to see if this solves your problem?

**Comment by aghaynes** [comment]
Sorry @vtraag, I have absolutely no idea where i was using this anymore... I should have included a reprex... live and learn I suppose...

**Comment by vtraag** [comment]
No problem, this happens!

**Pull request closed without merging**
