### PR TITLE
chore: restore igraph pointer

### PR DESCRIPTION
**Pull request by Antonov548**
Avoid populating igraph_t_idx_oi...igraph_t_idx_is in R

https://github.com/igraph/rigraph/issues/787

### CODE REVIEW

**Comment by Antonov548** [comment]
`R_igraph_get_pointer` restore pointer to igraph from R list structure in case pointer is lost. To restore pointer - `R_igraph_restore_pointer` is called.

The problem now with old graph structure.  Should `R_igraph_get_pointer` create new environment and restore pointer if R structure hasn't environment,?

**Review by krlmlr — APPROVED** [review]
Thanks. The code looks good. Why do the checks fail?

**Comment by Antonov548** [comment]
> Thanks. The code looks good. Why do the checks fail?

As I mentioned in comment, the problem with test check of old data type. In old data type there is no environment, so pointer couldn't be restored in environment. Maybe `update_graph` function should be updated?

**Comment by krlmlr** [comment]
Missed that. Perhaps `R_igraph_restore_pointer()` should be split:

- a function that recreates the native igraph object
- a function that adds the native igraph object to the environment

The second part would be called only if the environment exists. The problem is that we aren't really allowed to alter the structure of the object in-place.

I'm not sure what the practical consequences are. We could issue a warning in this case, and offer a way to manually upgrade the structure of the graph R object.

**Review by krlmlr — APPROVED** [review]
Looks good now, thanks! Please ping me if the next steps are unclear.

**Comment by krlmlr** [comment]
Please merge when good.

**Pull request merged**
