### PR TITLE
chore: Update generated interface

### LINKED ISSUE #752: Update Stimulus to generate the current code
The current state of this repository is the ground truth, minus perhaps whitespace. Need to update Stimulus so that this is generated automatically before upgrading the C library.

### PR DESCRIPTION
**Pull request by Antonov548**
Closes #752

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
Thanks! What happens if you run the updated Stimulus on this branch?

**Comment by Antonov548** [comment]
> Thanks! What happens if you run the updated Stimulus on this branch?

If I run updated stimulus from local path, there is not changes in git.

**Comment by Antonov548** [comment]
@krlmlr related Stimulus PR: https://github.com/igraph/stimulus/pull/2

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
