### PR TITLE
More serious (?) failure with stochastic test

### PR DESCRIPTION
**Pull request by krlmlr**
Similar to #579, but here an actual expectation fails. This seems to require a more thorough investigation.

### CODE REVIEW

**Comment by ntamas** [comment]
Linking igraph/igraph#2207 here as a possible source of nondeterminism

**Comment by szhorvat** [comment]
Just noting that the non-determinism (i.e. non-responsiveness to a seed set in R) was just one of the issues here. The main issue is of course that running this community-detection function twice in a row may produce different results. That calls into question the accuracy of the produced eigenvectors.

**Comment by ntamas** [comment]
I have backported the recent determinism-related ARPACK patches in igraph 0.10.x to the 0.9 branch and this failure now seems to be gone, at least on my machine. I'll commit this and merge the change proposed by @szhorvat re the iteration count and then we'll see how this fares in CI.

**Comment by ntamas** [comment]
CI passed with an updated C igraph core so I'm going to close this PR. Feel free to reopen if you find another issue similar to this.

**Comment by szhorvat** [comment]
Does the CI pass with _this_ modification though? WHat if you merge `dev` into this PR?

**Comment by ntamas** [comment]
I can't push commits to this PR, but it passes the tests locally on my computer, even with the modifications outlined here.

**Comment by szhorvat** [comment]
> I can't push commits to this PR

It's strange that it allowed me to edit from the web interface though.

**Pull request closed without merging**
