### PR TITLE
$ operator

### PR DESCRIPTION
**Pull request by ttriche**
as referenced in issue

### CODE REVIEW

**Comment by ttriche** [comment]
The ego-subgraph selection operation selects the subgraph s of graph g "around" vertex v, so 

g %around% v 

seemed like a reasonable syntactic compromise.   This addresses https://github.com/igraph/rigraph/issues/168

**Review by IgnatiusPang — COMMENTED** [review]
Could probably be replaced by magrittr pipe %>%. This is probably just a syntactic sugar and perhaps not a priority to merge.

**Comment by vtraag** [comment]
I think the crucial point was raised by @mbojan in https://github.com/igraph/rigraph/issues/168#issuecomment-246999705: how is this different from `make_ego_graph`? Indeed, he also suggests that this can simply be done by a `magrittr` pipe, similar to your observation @IgnatiusPang. 

I would be inclined to close this, unless somebody has good arguments for introducing such a functionality.

**Comment by ntamas** [comment]
Closing as suggested above by @vtraag

**Pull request closed without merging**
