### PR TITLE
docs: add more cdocs tags

### PR DESCRIPTION
**Pull request by maelle**
Part of #1317 

It's taking a while to run so I might have to start again on Monday but it's looking good so far.

### CODE REVIEW

**Comment by maelle** [comment]
mmh why can't it find a igraph entry for "igraph_eigen_adjacency"? It's listed in the YAML files.

**Comment by maelle** [comment]
oooh https://github.com/igraph/igraph/issues/2142

**Comment by szhorvat** [comment]
C🐶 🏷️ ?

**Comment by szhorvat** [comment]
I don't have much to add here. I think this should be merged, and improvements can be done later.

Some very minor things:

 - My personal preference would be to format C function names as `igraph_foo()` instead of `igraph_foo`. But either is fine, really.
 - There are a few prominent functions that seem to be missing, such as `betweenness()`.
 - Be aware that sometimes the link goes to a generic version of a C function, while some of the documentation is present in a more specific version. Examples are e.g. `igraph_harmonic_centrality_cutoff()` vs `igraph_harmonic_centrality()`, or `igraph_personalized_pagerank()` vs `igraph_pagerank()`. This is a necessary limitation of this imperfect approach, and I wouldn't worry about it now. A practical solution is to do more cross-referencing in the C docs. Overall, I expect that one major positive effect of this work will be a lot more feedback from users about the C docs

**Review by szhorvat — APPROVED** [review]

**Comment by maelle** [comment]
Thank you!

> My personal preference would be to format C function names as igraph_foo() instead of igraph_foo. But either is fine, really.

That's something I can fix!

> There are quite a few prominent functions that seem to be missing, such as betweenness(). When I browse functions randomly, most of the time I see no link to C docs.

`betweenness()` does not wrap an `_impl()` function hence its exclusion from this PR.

> Do you prefer the links to C docs to be in a bullet list (as they are now), or on a single compact line, similar to the "See Also" section? I am noting the difference between the two, but I don't have a clear preference.

Good idea, I'll look into this.

> Would it make sense to have this section directly above "See Also" instead of above "References"? Again, no strong preference from me.

I'm not sure this is something we can control.

> Be aware that sometimes the link goes to a generic version of a C function, while some of the documentation is present in a more specific version

It still sounds weird, I'll check.

**Comment by maelle** [comment]
In https://roxygen2.r-lib.org/articles/rd-formatting.html#sections-and-subsections

> Top level sections are placed at a fixed position in the manual page, after the parameters and the details, but before \note{}, \seealso{} and the \examples{}. Their order will be the same as in the roxygen block.

**Comment by maelle** [comment]
Regarding the "wrong" links for "igraph_harmonic_centrality" I only see:

```r
#' @cdocs igraph_harmonic_centrality_cutoff
harmonic_centrality <- harmonic_centrality_cutoff_impl
```

**Comment by maelle** [comment]
I'll regenerate then merge.

**Pull request merged**
