### PR TITLE
fix: `shortest.paths()` no longer fails

### PR DESCRIPTION
**Pull request by szhorvat**
@krlmlr Should fix most revdep failures.

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. I think we should `igraph.match.arg(algorithm)` instead. Why do you think this will fix many failures?

**Comment by szhorvat** [comment]
Because locally this fixed this error for me when using `shortest.paths()`:

```
Error in match.arg(arg = arg, choices = choices, several.ok = several.ok) : 
  'arg' must be of length 1
```

This was the majority of the revdep failures.

I fixed the bad docs now, hopefully CI passes

**Comment by szhorvat** [comment]
Please go ahead.

**Comment by krlmlr** [comment]
Fixes 32 out of 33 failures, the 33rd still running. Good catch, I'm so relieved!

**Pull request merged**
