### PR TITLE
Update vendored igraph/C to igraph/igraph@e1203464653cbcb5e87a16881ec…

### PR DESCRIPTION
**Pull request by Antonov548**
https://github.com/igraph/igraph/issues/2459

### CODE REVIEW

**Comment by szhorvat** [comment]
Thanks! Can you please test https://github.com/igraph/igraph/issues/2459 after merging this, _just in case_?

**Comment by Antonov548** [comment]
> Thanks! Can you please test [igraph/igraph#2459](https://github.com/igraph/igraph/issues/2459) after merging this, _just in case_?

I have tried this example locally. I don't see segfault compared to main branch.

**Comment by krlmlr** [comment]
I didn't see this, pushed to main.

**Comment by krlmlr** [comment]
Ideally, if we already have R code that tests this, why only test locally and not add a test that will make sure that the bug doesn't return?

**Comment by szhorvat** [comment]
> Ideally, if we already have R code that tests this, why only test locally and not add a test that will make sure that the bug doesn't return?

Of course. I didn't push it because I did add a test in C already. If you add a test in R, ideally it would use a different disconnected graph than what was in the original test case, to distinguish it from the C test case.

An invalid memory access should be triggered when requesting _only_ modularity and the graph is not connected.

**Pull request closed without merging**
