### PR TITLE
feat: Support `index = NULL` when setting attributes

### PR DESCRIPTION
**Pull request by krlmlr**
For #466. Two FIXMEs remain, to be addressed in a follow-up PR.

I'd like to propose to make attribute updates a bit stricter as part of this exercise: allow `value` only of length one or the same length as the index. While this is technically a breaking change, most uses of passing `value` of incompatible length are very likely a mistake. @ntamas: What do you think?

### CODE REVIEW

**Comment by ntamas** [comment]
Not sure; I can easily imagine people making use of the vector recycling feature of R to assign "perodic" vertex or edge attributes to graphs with a certain regular structure.

**Comment by krlmlr** [comment]
I did think about that, but I find it rather exotic, to be honest. Those users, if any, would need to use `rep()` beforehand. Can we get data from our users to drive this decision?

**Comment by krlmlr** [comment]
It doesn't complicate things, but I believe it's the right thing to do.

I have a few ideas how to make revdepchecks a less costly exercise.

**Comment by ntamas** [comment]
Any improvements to the revdepcheck process are welcome. Right now the biggest pain for me is that the revdepcheck process has to be babysitted because the revdepcheck process crashes randomly (with a segfault). Sometimes it's running for hours without problems, but every now and then it crashes, so I cannot just leave it running during the night and be done with it by the morning. I believe this is mostly due to running the revdepchecks over multiple CPU cores in parallel as the crashes never seem to happen when running on a single core only. Also, sometimes there are failures that happen when running the tests in parallel but they disappear when I start running them on a single thread only.

And of course there are always false positives due to network outages etc; they are somewhat cumbersome to deal with as you sometimes need to dig into the test output to understand what's happening and in 99% of the cases it's a waste of time.

**Pull request merged**
