### PR TITLE
CRAN release v1.4.3

### PR DESCRIPTION
**Pull request by krlmlr**
Release requested by R core.

### CODE REVIEW

**Comment by szhorvat** [comment]
Do you want to include a fix to #797 by renaming `merges` -> `cluster.merges`? This avoids the wrong result.

**Comment by krlmlr** [comment]
I have submitted this version already. Would fixing #797 mean risking downstream failures?

**Comment by szhorvat** [comment]
Yes it would, but any downstream test that fails is _likely_ (though not certain) to be invalid anyway.

**Comment by krlmlr** [comment]
The submission has been accepted. Added the issue to the plan for the next release.

**Comment by krlmlr** [comment]
@maelle: Should this have been closed by now by our fledge workflow?

**Comment by maelle** [comment]
@krlmlr The problem is the PR title, which doesn't start with `fledge:::cran_release_pr_title()` ("CRAN release v"). How was this PR created? I'll make a PR to fledge to add a more flexible regex.

**Comment by maelle** [comment]
(the PR title is used to get the version)

**Comment by krlmlr** [comment]
Thanks, changed the title. Don't necessarily need to change fledge for now. This was a manual PR from a tag. I wonder if fledge can offer tooling for this process too.

**Pull request merged**
