### PR TITLE
Graph imported from data.frame is not simplified

### PR DESCRIPTION
**Pull request by SamGG**
As discussed in #394, I would like to document that stating the graph as undirected does not imply that reversed links are aggregated automagically. I think that simplication could speed up some calculations. Let me know if you feel this addition informative.
Best.

### CODE REVIEW

**Comment by szhorvat** [comment]
Just a note that the purpose of simplification is *not* to speed up calculations.

When you are computing some graph measure, you need to consider:

 - Does it make sense at all for multigraphs?
 - If it does make sense, does igraph's implementation work for multigraphs?
 - If yes, does it make sense for your application (interpretation of the graph) to retain multi-edges? What is their interpretation? Retaining them does affect many graph measures, such as betweenness centrality.

I am not sure how @gaborcsardi feels about it, but personally I would remove "Simplifying the graph can speed up some calculations." because it might mislead some users.

**Comment by SamGG** [comment]
Being not experienced with graphs or multigraphs, I removed the speed up sentence.
Thanks for your feedback.

**Comment by SamGG** [comment]
Just for information, for Louvain algorithm, the simplified weighted graph leads to the same result than the original multigraph, with computation of 76 sec (including the simplification, 300 000 vertices, 6164839 edges) vs 102 sec (unsimplified, 8 646 579 edges).

**Comment by mbojan** [comment]
I am pretty sure that Louvain alg. ignores multiple edges (unless you "aggregate" the graph by counting edges within each dyad and use the counts as weights) and the slowdown is just because your handling a larger object memory-wise.

As we discussed in #394, and as @szhorvat writes above, simplifying the graph is not a pure efficiency matter. It is not appropriate to assume in general that if there are more than one edge within a dyad that all the extra edges are redundant from the data perspective. One popular usecase is social network analysis: you can have multiple edges between two nodes (persons) corresponding to different types of relations (say i is a friend of j, j is a boss of i, i often seeks advice from j and so on), which you would like to be able to analyze/visualize jointly

IMHO from the software perspective it is better not to assume what particular application is the data structure used for. It has always been in R tradition to empower the user with the responsibility of being explicit how the data should be processed (just like `NA`s require explicit treatment even if you want to compute a simple `mean()`).

**Comment by vtraag** [comment]
> I am pretty sure that Louvain alg. ignores multiple edges

The implementation actually loops over (incident) edges, so it does take into account multiple edges. Similarly, `igraph_modularity` loops over edges, so also considers multiple edges. FInally, `igraph_modularity_matrix` relies on `get_adjacency` which also considers multiple edges and entries will contain the edge multiplicities. Perhaps this can be explicitly stated in the documentation.

Regardless, as you and @szhorvat already stated
> simplifying the graph is not a pure efficiency matter. 
I agree completely.

**Comment by vtraag** [comment]
The original branch by @SamGG is deleted. It might still be useful to document explicitly that all edges are considered. I added this in 6524d0239432199a7b9fa819cc3b7cacc6d05a67.

**Pull request closed without merging**
