### PR TITLE
chore!: Remove some behaviour / parameters that were deprecated in 1.3

### PR DESCRIPTION
**Pull request by szhorvat**
Fixes the following deprecated behaviours / parameters:

 - #814 
 - #819
 - #816
 - #817

I judge these to be very low risk, as these have all triggered warnings in the past, and some of the parameters were actually non-functional.

I would suggest also including #815 and #818 but those are slightly higher risk. However, warnings are already in place for these as well.

Requires revdepchecks.

### CODE REVIEW

**Comment by krlmlr** [comment]
Reviewing this soon after the 1.5.0 release.

**Comment by szhorvat** [comment]
Some of the docs text will need to be adjusted, as it mentions that the change was made in "1.5".

**Comment by krlmlr** [comment]
Thanks. I'll pick it up from here and create individual PRs for your review.

**Comment by maelle** [comment]
I see this affects the same functions as #852.
To deprecate arguments shouldn't we follow https://lifecycle.r-lib.org/articles/communicate.html#arguments? That's what you mean by individual PRs @krlmlr? I could do that from next week.

**Comment by krlmlr** [comment]
Thanks, that would be great.

**Comment by krlmlr** [comment]
Thanks. Running revdepchecks now.

**Comment by krlmlr** [comment]
Thanks! No further action is needed here.

**Pull request merged**
