### PR TITLE
fix `%\>%` typo in vignettes

### PR DESCRIPTION
**Pull request by snowGlint**

### CODE REVIEW

**Comment by maelle** [comment]
Thank you!

**Comment by maelle** [comment]
@krlmlr should we merge anyway? or wait until we've fixed CI checks more generally?

**Comment by krlmlr** [comment]
I had asked @Antonov548 to tweak CI/CD so that it's green even if the checks fail. Fixing the checks will need more time.

**Comment by snowGlint** [comment]
In the two versions of the vignettes, all `%>%` have been written as `%\>%,` and  `$` has been written as `\$`. These should be corrected.

**Pull request merged**
